version: '3.4'

services:
  data.externalreference.in.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  data.externalreference.out.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
networks:
    default:
        external:
            name: sample_default